apiVersion: apps/v1
kind: StatefulSet # TODO: Set kind to StatefulSet
metadata: 
  name: gowebapp-mysql
  labels:
    app: gowebapp-mysql
    tier: backend
spec:
  serviceName: gowebapp-mysql # TODO: Set serviceName to gowebapp-mysql
  replicas: 1
  selector:
    matchLabels:
      app: gowebapp-mysql
      tier: backend
  template:
    metadata:
      labels:
        app: gowebapp-mysql
        tier: backend
    spec:
      containers:
      - name: gowebapp-mysql
        image: gowebapp-mysql:v1
        env:
        - name: MYSQL_ROOT_PASSWORD
        # value: mypassword
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 3306
        # In some IDEs, warnings are due to lack of resource limits.
        # Although not indicated in the lab instructions,
        # resource limits are set below.
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          exec:
          #  command: ["mysql", "-uroot", "-pmypassword", "-e", "use gowebapp; select count(*) from user"]
            command: ["bash", "-c", "mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e 'use gowebapp; select count(*) from user'"]
          initialDelaySeconds: 25
          periodSeconds: 10
          timeoutSeconds: 1
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql # TODO: Set mountPath to /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi # TODO: Set storage request to 1Gi