#
# Before proceeding with the ff. instructions make sure that the JAR for this project 
# has been generated.
#
# 1. Use eclipse-temurin:17-jre as the base image
# 2. The WORKDIR must be in /app
# 3. Copy the JAR to the current working directory
# 4. The JAR file must be run during the "entrypoint"
# 5. Document the usage of the port 8080
# 6. Set the JDBC_URL environment variable to "jdbc:url"
# 7. Build the container with name:tag "pingservice:0.0.1"
#
